---
- name: Query Devices and Get Model/Serial Numbers 
  hosts: ios
  connection: local
  gather_facts: no
  
  tasks:

  - name: Gather Cisco IOS Hardware Facts
    ios_facts:
      gather_subset:
        - hardware
    register: facts_results

#  - name: Display contentes of ios_facts variable
#    debug:
#      var: vars

  - name: Create Output Directory
    file:
     path: "{{ dest_dir }}"
     recurse: yes
     state: directory

  - name: Output Results to File
    template:
      src: "templates/inventory.j2"
      dest: "{{ dest_dir }}/{{ ansible_facts.net_hostname }}-inventory.txt"
