---
# This will provide the variables/values below to all hosts

ansible_connection: network_cli
ansible_network_os: "{{ os }}"
ansible_user: "{{ vault_username }}"
ansible_ssh_pass: "{{ vault_password }}"
ansible_become: yes
ansible_become_method: enable

# Uncomment one of the below if you use different secret passwords based on device roles
# AND you do not define these variables in you inventory
#ansible_become_pass: "{{ vault_access_secret }}"
#ansible_become_pass: "{{ vault_distro_secret }}"

# This is where the individual host inventories will go
dest_dir: "configs/inventories"
