---
# This will provide the variables/values below to all hosts

ansible_connection: network_cli
ansible_network_os: "{{ os }}"
ansible_user: "{{ vault_username }}"
ansible_ssh_pass: "{{ vault_password }}"
ansible_become: yes
ansible_become_method: enable

# This is where the individual host inventories will go
dest_dir: "configs/inventories"
